//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>In general CachingProcessor might not use CurrencyProvider</remarks>
public class CachingProcessor : ICachingProcessor
{
	public virtual ICurrencyProvider ICurrencyProvider
	{
		get;
		set;
	}

	public virtual ICurrencyRepository ICurrencyRepository
	{
		get;
		set;
	}

}

