//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CurrencyExplorer
{
	private DataProcessor _dataProcessor
	{
		get;
		set;
	}

	private DataPresenter _dataPresenter
	{
		get;
		set;
	}

}

